"""
Django settings for prayer_room_api project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import sentry_sdk
from cbs import BaseSettings, env
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ROOT_URLCONF = "prayer_room_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR / "prayer_room_api" / "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "prayer_room_api.context_processors.site_content",
            ],
        },
    },
]

WSGI_APPLICATION = "prayer_room_api.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [str(BASE_DIR / "prayer_room_api" / "static")]

TAILWIND_CLI_SRC_CSS = "prayer_room_api/static/src/input.css"
TAILWIND_CLI_DIST_CSS = "css/tailwind.css"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

SENTRY_DSN = os.environ.get("SENTRY_DSN")

if SENTRY_DSN:

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        # Add data like request headers and IP for users,
        # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
        send_default_pii=True,
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for tracing.
        traces_sample_rate=1.0,
        _experiments={
            # Set continuous_profiling_auto_start to True
            # to automatically start the profiler on when
            # possible.
            "continuous_profiling_auto_start": True,
        },
        environment=os.environ.get("DJANGO_MODE"),
    )
    from sentry_sdk.integrations.logging import ignore_logger

    ignore_logger("django.security.DisallowedHost")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "null": {
            "level": "DEBUG",
            "class": "logging.NullHandler",
            "formatter": "verbose",
        },
    },
    "root": {"level": "INFO", "handlers": ["console"]},
    "loggers": {
        "django.db.backends": {
            "level": "ERROR",
            "handlers": ["console"],
            "propagate": False,
        },
        # Errors logged by the SDK itself
        "sentry_sdk": {"level": "ERROR", "handlers": ["console"], "propagate": False},
        "django.security.DisallowedHost": {
            "level": "ERROR",
            "handlers": ["null"],
            "propagate": False,
        },
    },
}


class Settings(BaseSettings):

    # Allow production to override the secret key, but fall-back to something consistent.
    SECRET_KEY = env(
        "django-insecure-y&^-#s$ee58d8&&xi_9kl1^38x)!0-1hgby+ofhdl23$8d6)$u"
    )

    # Email Configuration - Console backend for development
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = env(
        "Prayer Room <prayer@akmiller.co.uk>", key="DEFAULT_FROM_EMAIL"
    )

    # Public-facing base URL used to build absolute links in outgoing emails
    # (digests, notifications). Override per-deployment via env var.
    SITE_BASE_URL = env("http://localhost:8001", key="SITE_BASE_URL")

    # DEBUG defaults to True, but can be overridden by env var `DJANGO_DEBUG`
    DEBUG = env.bool(True, prefix="DJANGO_")

    # Simple cases that don't need `self` can even use a lambda
    MEDIA_ROOT = env(lambda self: BASE_DIR / "media")

    # Methods will be transparently invoked by the __getattr__ implementation
    def INSTALLED_APPS(self):
        return list(
            filter(
                None,
                [
                    "django.contrib.admin",
                    "django.contrib.auth",
                    "django.contrib.contenttypes",
                    "django.contrib.sessions",
                    "django.contrib.messages",
                    "django.contrib.staticfiles",
                    # Conditionally include an app
                    "debug_toolbar" if self.DEBUG else None,
                    "import_export",
                    "rest_framework",
                    "rest_framework.authtoken",
                    "corsheaders",
                    "django_extensions",
                    "django_htmx",
                    "neapolitan",
                    "django_filters",
                    "django_prodserver",
                    "django_tailwind_cli",
                    "prayer_room_api",
                ],
            )
        )

    def MIDDLEWARE(self):
        return list(
            filter(
                None,
                [
                    "django.middleware.security.SecurityMiddleware",
                    "django.contrib.sessions.middleware.SessionMiddleware",
                    "corsheaders.middleware.CorsMiddleware",
                    "django.middleware.common.CommonMiddleware",
                    "django.middleware.csrf.CsrfViewMiddleware",
                    "django.contrib.auth.middleware.AuthenticationMiddleware",
                    "django.contrib.messages.middleware.MessageMiddleware",
                    "django.middleware.clickjacking.XFrameOptionsMiddleware",
                    "django_htmx.middleware.HtmxMiddleware",
                    (
                        "whitenoise.middleware.WhiteNoiseMiddleware"
                        if not self.DEBUG
                        else False
                    ),
                    # Conditionally include a middleware
                    (
                        "debug_toolbar.middleware.DebugToolbarMiddleware"
                        if self.DEBUG
                        else False
                    ),
                ],
            )
        )

    # Parse the URL into a database config dict.
    DEFAULT_DATABASE = env.dburl("sqlite:///db.sqlite3")

    CORS_ALLOWED_ORIGINS = [
        "http://localhost:4000",
        "http://localhost:5173",
    ]

    ALLOWED_HOSTS = []

    INTERNAL_IPS = ["localhost", "127.0.0.1"]

    def DATABASES(self):
        return {
            "default": self.DEFAULT_DATABASE,
        }

    def PRODUCTION_PROCESSES(self):
        return {
            "web": {
                "BACKEND": "django_prodserver.backends.gunicorn.GunicornServer",
                "ARGS": {
                    "bind": f"0.0.0.0:{os.environ.get('PORT', '8000')}",
                },
            },
        }


class StagingSettings(Settings):
    # Override
    DEBUG = False

    # Values that *must* be provided in the environment.
    STATIC_ROOT = env(env.Required)
    SITE_BASE_URL = env(env.Required, key="SITE_BASE_URL")
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

    CORS_ALLOWED_ORIGINS = []
    CORS_ALLOWED_ORIGIN_REGEXES = [r"https://[\w-]+-\d+--prayer-room\.netlify\.app"]

    ALLOWED_HOSTS = ["staging-prayer-room-api.dokku.akmiller.co.uk"] + [
        f"172.17.0.{num}" for num in range(2, 255)
    ]

    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    EMAIL_BACKEND = "anymail.backends.amazon_ses.EmailBackend"
    DEFAULT_FROM_EMAIL = env(
        "STAGING Prayer Room <prayer@akmiller.co.uk>", key="DEFAULT_FROM_EMAIL"
    )

    def ANYMAIL(self):
        return {
            "AMAZON_SES_CLIENT_PARAMS": {
                "region_name": os.environ.get("AWS_SES_REGION", "eu-west-2"),
            },
        }


class ProdSettings(Settings):
    # Override
    DEBUG = False

    # Values that *must* be provided in the environment.
    STATIC_ROOT = env(env.Required)
    SITE_BASE_URL = env(env.Required, key="SITE_BASE_URL")
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

    CORS_ALLOWED_ORIGINS = ["https://prayer.akmiller.co.uk"]

    ALLOWED_HOSTS = ["prayer-room.dokku.akmiller.co.uk"] + [
        f"172.17.0.{num}" for num in range(2, 255)
    ]

    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Email Configuration - AWS SES via django-anymail
    EMAIL_BACKEND = "anymail.backends.amazon_ses.EmailBackend"
    DEFAULT_FROM_EMAIL = env(
        "Prayer Room <prayer@akmiller.co.uk>", key="DEFAULT_FROM_EMAIL"
    )

    def ANYMAIL(self):
        return {
            "AMAZON_SES_CLIENT_PARAMS": {
                "region_name": os.environ.get("AWS_SES_REGION", "eu-west-2"),
            },
        }


# The `use` method will find the right sub-class of ``BaseSettings`` to use
# Based on the value of the `DJANGO_MODE` env var.
__getattr__, __dir__ = Settings.use()
